run:
  allow-parallel-runners: true
  timeout: 3m

output:
  sort-results: true

severity:
  default-severity: warning

linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    - funlen
    - exhaustruct
    - exhaustivestruct
    - ireturn
    - nlreturn
    - nonamedreturns
    - varnamelen
    - wsl

linters-settings:
  cyclop:
    skip-tests: true
  revive:
    severity: error
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true
      - name: argument-limit
        disabled: true
      - name: banned-characters
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: file-header
        disabled: true
      - name: function-length
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: get-return
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: package-comments
        disabled: false
